version: '3.8'

services:
  twilio_api:
    container_name: twilio_api
    image: twilio/api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - twilio_db
    env_file:
      - .env.api
    environment:
      FASTIFY_PORT: 1337
    networks:
      - twilio-network
    ports:
      - 1337:1337
    restart: always
    volumes:
      - ./packages/api:/usr/src/app
      - /usr/src/app/node_modules

  twilio_ui:
    container_name: twilio_ui
    image: twilio/ui:latest
    build:
      context: .
      dockerfile: Dockerfile.ui
    depends_on:
      - twilio_api
    env_file:
      - .env.ui
    networks:
      - twilio-network
    ports:
      - 3000:80
    restart: always
    volumes:
      - ./packages/ui:/usr/src/app
      - /usr/src/app/node_modules

  twilio_db:
    container_name: twilio_db
    image: mongo:4.2.22
    restart: always
    env_file:
      - .env.db
    networks:
      - twilio-network
    ports:
      - 27017:27017
    volumes:
      - .tmp/mongo:/data/db
      - .docker/mongo-entrypoint:/docker-entrypoint-initdb.d

networks:
  twilio-network:
