version: '3.8'

services:
  twilio_api:
    container_name: twilio_api
    image: twilio/api:latest
    build:
      context: packages/api
      dockerfile: Dockerfile
    depends_on:
      - twilio_db
    env_file:
      - packages/api/.env.docker
    environment:
      FASTIFY_PORT: 1337
      FASTIFY_ADDRESS: 0.0.0.0
    networks:
      - twilio-network
    ports:
      - 1337:1337
    restart: always
    volumes:
      - ./packages/api:/usr/src/app
      - /usr/src/app/node_modules

  twilio_ui:
    container_name: twilio_ui
    image: twilio/ui:latest
    build:
      context: packages/ui
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://twilio_api:1337}
    depends_on:
      - twilio_api
    env_file:
      - packages/ui/.env.docker
    networks:
      - twilio-network
    ports:
      - 3000:80
    restart: always
    volumes:
      - ./packages/ui:/usr/src/app
      - /usr/src/app/node_modules

  twilio_db:
    container_name: twilio_db
    image: mongo:4.2.22
    restart: always
    env_file:
      - .env.db
    networks:
      - twilio-network
    ports:
      - 27017:27017
    volumes:
      - .tmp/mongo:/data/db
      - .docker/mongo-entrypoint:/docker-entrypoint-initdb.d

networks:
  twilio-network:
