version: '3.8'

services:
  api:
    container_name: twilio_api
    image: twilio/api:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
      - .env.docker
    environment:
      API_FRONTEND_URL: ${API_FRONTEND_URL:-http://localhost:3000}
      API_MONGO_URL: ${API_MONGO_URL:-mongodb://userusername:userpassword@mongo:27017/ruleOfThumb}
    networks:
      - twilio-network
    ports:
      - 1337:1337
    restart: always
    volumes:
      - packages/api:/usr/src/app
      - /usr/src/app/node_modules

  ui:
    container_name: twilio_ui
    image: twilio/ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
      - .env.docker
    environment:
      UI_BACKEND_URL: ${UI_BACKEND_URL:-http://localhost:1337}
    networks:
      - twilio-network
    ports:
      - 3000:3000
    restart: always
    volumes:
      - packages/ui:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    container_name: twilio_db
    image: mongo:4.2.22
    restart: always
    env_file:
      - .env.docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-adminuser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-adminpassword}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-twilio}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME:-userusername}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD:-userpassword}
    networks:
      - twilio-network
    ports:
      - 27017:27017
    volumes:
      - .tmp/mongo:/data/db
      - .bin/mongo-entrypoint:/docker-entrypoint-initdb.d

networks:
  twilio-network:
