version: '3.8'

services:
  twilio_api:
    container_name: twilio_api
    image: twilio/api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - twilio_db
    env_file:
      - ./.env
    environment:
      FRONTEND_URL: ${API_FRONTEND_URL:-http://twilio_ui:3000}
      MONGO_URL: ${API_MONGO_URL:-mongodb://twilioUsername:twilioPassword@twilio_db:27017/twilioDatabase}
      TWILIO_ACCOUNT_SID: ${API_TWILIO_ACCOUNT_SID:-''}
      TWILIO_AUTH_TOKEN: ${API_TWILIO_AUTH_TOKEN:-''}
      TWILIO_VERIFY_SERVICE_SID: ${API_TWILIO_VERIFY_SERVICE_SID:-''}
    networks:
      - twilio-network
    ports:
      - 1337:1337
    restart: always
    volumes:
      - ./packages/api:/usr/src/app
      - /usr/src/app/node_modules

  twilio_ui:
    container_name: twilio_ui
    image: twilio/ui:latest
    build:
      context: .
      dockerfile: Dockerfile.ui
    depends_on:
      - twilio_api
    env_file:
      - ./.env
    environment:
      VITE_BACKEND_URL: ${UI_BACKEND_URL:-http://localhost:1337}
    networks:
      - twilio-network
    ports:
      - 3000:80
    restart: always
    volumes:
      - ./packages/ui:/usr/src/app
      - /usr/src/app/node_modules

  twilio_db:
    container_name: twilio_db
    image: mongo:4.2.22
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-adminuser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-adminpassword}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-twilioDatabase}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME:-twilioUsername}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD:-twilioPassword}
    networks:
      - twilio-network
    ports:
      - 27017:27017
    volumes:
      - .tmp/mongo:/data/db
      - .bin/mongo-entrypoint:/docker-entrypoint-initdb.d

networks:
  twilio-network:
